FROM espressif/idf:release-v5.3

WORKDIR /usr/src/app

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y -q update && apt-get install -y -q \
    libgcrypt20 \
    libglib2.0-0 \
    libpixman-1-0 \
    libslirp0 \
    python3-venv \
    pkg-config \
    libglib2.0-dev \
    cmake \
    ninja-build \
    python3-pip
RUN pip install platformio
RUN platformio platform install espressif32 --with-package framework-arduinoespressif32

COPY . /usr/src/app/

RUN git config --global --add safe.directory /usr/src/app
ENV IDF_PATH=/opt/esp/idf
ENV PATH=$IDF_PATH:IDF_PATH/tools:$PATH

RUN echo ". /opt/esp/idf/export.sh" >> /root/.profile 

WORKDIR /usr/src/app
RUN platformio run --silent