name: Build Firmware

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull witcher-firmware-dev container
      run: docker pull ghcr.io/witcher-firmware/witcher-firmware-dev:latest
    
    - name: Build firmware in container
      run: |
        docker run --rm \
        -v ${{ github.workspace }}:/workspace \
        -w /workspace \
        ghcr.io/witcher-firmware/witcher-firmware-dev:latest \
        make -j$(nproc) firmware