name: Build Firmware

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main 

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/bradley-evans/witcher-firmware/witcher-firmware-dev:latest
      options: --privileged
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 
    permissions:
      packages: read

    steps:    
    - name: Build firmware in container
      run: make -j$(nproc) firmware